name: Forms
type: Starshot
description: Provides a simple contact form, and tools for building more complex forms.
install:
  - antibot
  - honeypot
  - webform
  - webform_ui
config:
  import:
    webform: '*'
  actions:
    honeypot.settings:
      simple_config_update:
        # Protect the user registration form, password reset form, and
        # comment form using Honeypot, since those are fairly likely to
        # be exposed to anonymous users.
        form_settings.comment_comment_form: true
        form_settings.user_pass: true
        form_settings.user_register_form: true
    user.role.authenticated:
      grantPermissions:
        - 'bypass honeypot protection'
        - 'skip antibot'
    webform.webform.contact:
      setThirdPartySettings:
        -
          module: antibot
          key: antibot
          value: true
        -
          module: honeypot
          key: honeypot
          value: true
