x-volumes:
  &default-volumes
    # Define all volumes you would like to have real-time mounted into the docker containers
    volumes:
      - app:/app


x-environment:
  &default-environment
    LAGOON_ROUTE: &default-url http://${COMPOSE_PROJECT_NAME:-drupal-cms-example}.docker.amazee.io
    # Change to "production" to have the system behave like in production
    # LAGOON_ENVIRONMENT_TYPE: development
    # Uncomment to enable xdebug and then restart via `docker-compose up -d`
    #XDEBUG_ENABLE: "true"

x-user:
  &default-user
    # The default user under which the containers should run. Change this if you are on linux and run with another user than id `1000`
    user: '1000'

volumes:
  app:
    labels:
      lagoon.type: persistent
  files:
    labels:
      lagoon.type: persistent
  composer-cache:
    labels:
      lagoon.type: persistent
      lagoon.backup: false
  db:
    {}

services:

  cli: # cli container, will be used for executing composer and any local commands (drush, drupal, etc.)
    build:
      context: .
      target: cli
      dockerfile: .lagoon/Dockerfile
    labels:
      # Lagoon Labels
      lagoon.type: cli
      lagoon.volumes.app.path: /app/
      # lagoon.volumes.files.path: /app/web/sites/default/
      lagoon.volumes.composer-cache.path: /home/.composer/cache/
      lando.type: php-cli-drupal
    << : [*default-volumes, *default-user]
    environment:
      << : *default-environment # loads the defined environment variables from the top

  nginx:
    build:
      context: .
      target: nginx
      dockerfile: .lagoon/Dockerfile
    labels:
      lagoon.type: nginx-php
      lagoon.volumes.app.path: /app/
      # lagoon.volumes.files.path: /app/web/sites/default/
      lando.type: nginx-drupal
    ports:
      - "8080" # exposes the port 8080 with a random local port, find it with `docker compose port nginx 8080`
    << : [*default-volumes, *default-user]
    depends_on:
      - cli # basically just tells docker-compose to build the cli first
    environment:
      << : *default-environment # loads the defined environment variables from the top
      LAGOON_LOCALDEV_URL: *default-url
    networks:
      - amazeeio-network
      - default

  php:
    build:
      context: .
      target: php
      dockerfile: .lagoon/Dockerfile
    labels:
      lagoon.type: nginx-php
      lagoon.name: nginx # we want this service be part of the nginx pod in Lagoon
      lagoon.volumes.app.path: /app/
      # lagoon.volumes.files.path: /app/web/sites/default/
      lagoon.volumes.composer-cache.path: /home/.composer/cache/
      lando.type: php-fpm
    << : [*default-volumes, *default-user]
    depends_on:
      - cli # basically just tells docker-compose to build the cli first
    environment:
      << : *default-environment # loads the defined environment variables from the top

  mariadb:
    image: uselagoon/mariadb-10.11-drupal:latest
    labels:
      lagoon.type: mariadb-single
      lando.type: mariadb-drupal
    ports:
      - "3306" # exposes the port 3306 with a random local port, find it with `docker compose port mariadb 3306`
    << : *default-user # uses the defined user from top
    environment:
      << : *default-environment
    volumes:
      - db:/var/lib/mysql

networks:
  amazeeio-network:
    external: true
