name: Drupal CMS
description: Applies all the Drupal CMS recipes.
type: Drupal CMS
recipes:
  - basic_block_type
  - content_search
  - core_recommended_performance
  - core_recommended_maintenance
  - core_recommended_front_end_theme
  - user_picture
  # Provides a fallback text format which is available to all users.
  - restricted_html_format
  # Not in Standard...
  - remote_video_media_type
  - starshot_admin_theme
  - starshot_audio_media_type
  - starshot_blog
  - starshot_basic_html_editor
  - starshot_document_media_type
  - starshot_event_content_type
  - starshot_forms
  - starshot_full_html_editor
  - starshot_image_media_type
  - starshot_local_video_media_type
  - starshot_page_content_type
install:
  - menu_link_content
  - redirect
  # The rest of these are in Standard.
  - help
  - history
  - config
  - contextual
  - menu_link_content
  - datetime
  - menu_ui
  - options
  - shortcut
  - toolbar
  - field_ui
  - views_ui
config:
  import:
    help:
      - search.page.help_search
    image:
      - image.style.large
      - image.style.thumbnail
    node:
      - views.view.archive
      - views.view.content
      - views.view.content_recent
      - views.view.frontpage
      - views.view.glossary
    olivero:
      - block.block.olivero_help
      - block.block.olivero_search_form_narrow
      - block.block.olivero_search_form_wide
      - block.block.olivero_syndicate
    shortcut:
      - shortcut.set.default
    user:
      - core.entity_view_mode.user.compact
      - search.page.user_search
      - views.view.user_admin_people
      - views.view.who_s_new
      - views.view.who_s_online
  actions:
    node.type.blog:
      # Don't allow blog posts to have menu links by default, since that's
      # not normally what blog posts are for.
      setThirdPartySettings:
        -
          module: menu_ui
          key: available_menus
          value: []
        -
          module: menu_ui
          key: parent
          value: ''
    user.role.content_editor:
      grantPermissionsForEachMediaType:
        - 'create %bundle media'
        - 'delete own %bundle media'
        - 'edit own %bundle media'
      grantPermissionsForEachNodeType:
        - 'translate %bundle node'
        # These are in Standard.
        - 'create %bundle content'
        - 'delete %bundle revisions'
        - 'delete own %bundle content'
        - 'edit own %bundle content'
    # This view is confusing alongside the media views; there's really no
    # need to keep it around.
    views.view.files:
      delete: ~
    # This is all in Standard.
    node.settings:
      simple_config_update:
        # @todo Remove `langcode` once https://drupal.org/i/3427564 lands.
        langcode: en
        use_admin_theme: true
    user.role.authenticated:
      grantPermission: 'delete own files'
    user.role.anonymous:
      # This recipe assumes all published content should be publicly accessible.
      grantPermission: 'access content'
    user.settings:
      simple_config_update:
        verify_mail: true
        register: visitors_admin_approval
        cancel_method: user_cancel_block
