name: Drupal Suite
description: Applies all the Drupal Suite recipes.
type: Drupal Suite
recipes:
  - audio_media_type
  - document_media_type
  - editorial_workflow
  - image_media_type
  - local_video_media_type
  - remote_video_media_type
  - standard
  - starshot_article_content_type
  - starshot_basic_html_editor
  - starshot_full_html_editor
  - starshot_page_content_type
install:
  - coffee
  - menu_link_content
  - navigation
  - redirect
config:
  import:
    navigation: '*'
