name: Drupal Suite
description: Applies all the Drupal Suite recipes.
type: Drupal Suite
recipes:
  - audio_media_type
  - document_media_type
  - image_media_type
  - local_video_media_type
  - remote_video_media_type
  - standard
  - starshot_article_content_type
  - starshot_basic_html_editor
  - starshot_full_html_editor
  - starshot_page_content_type
install:
  - coffee
  - menu_link_content
  - navigation
  - redirect
config:
  import:
    navigation: '*'
  actions:
    user.role.content_editor:
      grantPermissions:
        - 'access coffee'
        - 'access shortcuts'
        - 'create content translations'
        - 'delete content translations'
        - 'update content translations'
        - 'use editorial transition archive'
        - 'use editorial transition create_new_draft'
        - 'use editorial transition publish'
        - 'use editorial transition archived_published'
        - 'use editorial transition archived_draft'
        - 'use text format basic_html'
        - 'use text format full_html'
        - 'use text format restricted_html'
        - 'view own unpublished media'
      grantPermissionsForEachMediaType:
        - 'create %bundle media'
        - 'delete own %bundle media'
        - 'edit own %bundle media'
      grantPermissionsForEachNodeType:
        - 'translate %bundle node'
