name: Drupal Suite
description: Applies all the Drupal Suite recipes.
type: Drupal Suite
recipes:
  - audio_media_type
  - document_media_type
  - editorial_workflow
  - image_media_type
  - local_video_media_type
  - remote_video_media_type
  - standard
install:
  - coffee
  - content_moderation
  - field
  - linkit
  - menu_link_content
  - metatag
  - navigation
  - path
  - pathauto
  - redirect
  - starshot
  - token
  - workflows
config:
  import:
    linkit:
      - image.style.linkit_result_thumbnail
    navigation: '*'
  actions:
    core.entity_form_display.node.article.default:
      setComponent:
        name: field_meta_tags
        options:
          type: metatag_firehose
          weight: 121
          region: content
          settings:
            sidebar: true
            use_details: true
    core.entity_form_display.node.page.default:
      setComponent:
        name: field_meta_tags
        options:
          type: metatag_firehose
          weight: 121
          region: content
          settings:
            sidebar: true
            use_details: true
    core.entity_view_display.node.article.default:
      setComponent:
        name: field_meta_tags
        options:
          type: metatag_empty_formatter
          label: above
          settings: { }
          third_party_settings: { }
          weight: 111
          region: content
    core.entity_view_display.node.page.default:
      setComponent:
        name: field_meta_tags
        options:
          type: metatag_empty_formatter
          label: above
          settings: { }
          third_party_settings: { }
          weight: 111
          region: content
    # Enable LinkIt in the basic_html and full_html formats, with its
    # default settings.
    editor.editor.basic_html:
      addPlugin:
        id: linkit_extension
        configuration:
          linkit_enabled: true
          linkit_profile: default
    editor.editor.full_html:
      addPlugin:
        id: linkit_extension
        configuration:
          linkit_enabled: true
          linkit_profile: default
    filter.format.basic_html:
      setFilterConfig:
        instance_id: linkit
        configuration:
          id: linkit
          status: true
    filter.format.full_html:
      setFilterConfig:
        instance_id: linkit
        configuration:
          id: linkit
          status: true
    metatag.settings:
      simple_config_update:
        entity_type_groups:
          node:
            article:
              basic: basic
            page:
              basic: basic
    workflows.workflow.editorial:
      addNodeTypes: '*'
