name: Drupal Suite
description: Applies all the Drupal Suite recipes.
type: Drupal Suite
recipes:
  - audio_media_type
  - document_media_type
  - editorial_workflow
  - image_media_type
  - local_video_media_type
  - remote_video_media_type
  - standard
install:
  - content_moderation
  - path
  - pathauto
  - redirect
  - token
  - workflows
config:
  actions:
    workflows.workflow.editorial:
      addNodeTypes: '*'
