name: Admin Theme
type: Drupal CMS
description: Sets up a nice administrative theme and navigation.
install:
  - coffee
  - gin
  - gin_toolbar
  - navigation
  - sam
config:
  import:
    gin: '*'
    navigation: '*'
  actions:
    system.theme:
      simple_config_update:
        admin: gin
