name: Article
type: Starshot
description: 'Adds pretty URLs, moderation, scheduling, translation, and meta tags to the Article content type.'
recipes:
  - editorial_workflow
  - article_content_type
install:
  - content_translation
  - field
  - language
  - metatag
  - path
  - pathauto
  - scheduler
  - token
  - views
  - workflows
config:
  import:
    language: '*'
    scheduler: '*'
  actions:
    core.entity_form_display.node.article.default:
      setComponents:
        - name: field_meta_tags
          options:
            type: metatag_firehose
            weight: 121
            region: content
            settings:
              sidebar: true
              use_details: true
        - name: scheduler_settings
          options:
            weight: 13
            region: content
        - name: publish_on
          options:
            type: datetime_timestamp_no_default
            weight: 14
            region: content
        - name: unpublish_on
          options:
            type: datetime_timestamp_no_default
            weight: 15
            region: content
    core.entity_view_display.node.article.default:
      setComponent:
        name: field_meta_tags
        options:
          type: metatag_empty_formatter
          label: above
          settings: { }
          third_party_settings: { }
          weight: 111
          region: content
    metatag.settings:
      simple_config_update:
        entity_type_groups.node.article.basic: basic
    node.type.article:
      setThirdPartySettings:
        - module: scheduler
          key: expand_fieldset
          value: when_required
        - module: scheduler
          key: fields_display_mode
          value: vertical_tab
        - module: scheduler
          key: publish_enable
          value: true
        - module: scheduler
          key: publish_past_date
          value: error
        - module: scheduler
          key: publish_past_date_created
          value: false
        - module: scheduler
          key: publish_required
          value: false
        - module: scheduler
          key: publish_revision
          value: true
        - module: scheduler
          key: publish_touch
          value: true
        - module: scheduler
          key: show_message_after_update
          value: true
        - module: scheduler
          key: unpublish_enable
          value: true
        - module: scheduler
          key: unpublish_required
          value: false
        - module: scheduler
          key: unpublish_revision
          value: true
    workflows.workflow.editorial:
      addNodeTypes:
        - article
