name: Blog
type: Starshot
description: 'Sets up a basic blog, with tagging and commenting.'
recipes:
  - comment_base
  - editorial_workflow
  - starshot_image_media_type
  - tags_taxonomy
install:
  - content_translation
  - language
  - metatag
  - node
  - path
  - pathauto
  - scheduler
  - token
  - views
  - workflows
config:
  import:
    image:
      # Only import config which is also imported by the Standard profile.
      - image.style.medium
      - image.style.thumbnail
      - image.style.wide
    language: '*'
    node:
      # Only import config which is also imported by the Standard profile.
      - core.entity_view_mode.node.full
      - core.entity_view_mode.node.rss
      - core.entity_view_mode.node.teaser
      - field.storage.node.body
      - system.action.node_delete_action
      - system.action.node_make_sticky_action
      - system.action.node_make_unsticky_action
      - system.action.node_promote_action
      - system.action.node_publish_action
      - system.action.node_save_action
      - system.action.node_unpromote_action
      - system.action.node_unpublish_action
    scheduler:
      - views.view.scheduler_scheduled_content
    taxonomy:
      - views.view.taxonomy_term
  actions:
    metatag.settings:
      simple_config_update:
        entity_type_groups.node.blog.basic: basic
    workflows.workflow.editorial:
      addNodeTypes:
        - blog
